opt_in_rules:
    - anyobject_protocol
    - contains_over_first_not_nil
    - attributes
    - closure_end_indentation
    - closure_spacing
    - collection_alignment
    - conditional_returns_on_newline
    - discouraged_object_literal
    - discouraged_optional_boolean
    - empty_count
    - empty_string
    - empty_xctest_method
    - first_where
    - force_unwrapping
    - identical_operands
    - last_where
    - legacy_random
    - let_var_whitespace
    - literal_expression_end_indentation
    - lower_acl_than_parent
    - multiline_arguments_brackets
    - multiline_function_chains
    - multiline_literal_brackets
    - operator_usage_whitespace
    - overridden_super_call
    - prohibited_super_call
    - redundant_nil_coalescing
    - redundant_type_annotation
    - sorted_first_last
    - toggle_bool
    - unowned_variable_capture
    - untyped_error_in_catch
    - vertical_parameter_alignment_on_call
    - vertical_whitespace_between_cases
    - yoda_condition
    
disabled_rules:
    - trailing_whitespace

excluded:
    - Pods
    - Configurations

# configurable rules can be customized
# idiomatic
force_cast:
    severity: warning
force_try:
    severity: warning
empty_count:
    severity: warning
shorthand_operator:
    severity: warning
# metrics
closure_body_length:
    warning: 20
line_length:
    warning: 400
    error: 600
function_body_length:
    warning: 80
cyclomatic_complexity:
    warning: 50
function_parameter_count:
    warning: 6
large_tuple:
    warning: 5
nesting:
    type_level:
        warning: 3
    statement_level:
        warning: 5

# style
identifier_name:
    min_length:
        warning: 1
    max_length:
        warning: 40
    allowed_symbols:
        - "_"
